escola/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gerenciamento/', include('gerenciamento.urls')),
]

gerenciamento/urls.py
from django.urls import path
from .views import lista_alunos, lista_cursos, lista_matriculas

urlpatterns = [
    path('aluno/', lista_alunos, name='lista_alunos'),
    path('curso/', lista_cursos, name='lista_cursos'),
    path('matriculas/', lista_matriculas, name='lista_matriculas'),
]

gerenciamento/models.py
from django.db import models

# Create your models here.
from django.db import models

class Aluno(models.Model):
    nome = models.CharField(max_length=100)
    data_nascimento = models.DateField()

    def __str__(self):
        return self.nome

class Curso(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField()

    def __str__(self):
        return self.nome

class Matricula(models.Model):
    aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    data_matricula = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.aluno} matriculado em {self.curso}'

gerenciamento/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from .models import Aluno, Curso, Matricula

def lista_alunos(request):
    alunos = Aluno.objects.all()
    return render(request, 'lista_alunos.html', {'alunos': alunos})

def lista_cursos(request):
    cursos = Curso.objects.all()
    return render(request, 'lista_cursos.html', {'cursos': cursos})

def lista_matriculas(request):
    matriculas = Matricula.objects.all()
    return render(request, 'lista_matriculas.html', {'matriculas': matriculas})

gerenciamento/templates/alunos/atualizar_alunos.html
<h1>Atualizar Alunos</h1>
<form method="post">
    {% csrf_token %}
    <div>
        <label for="id_nome">Nome:</label>
        <input type="text" id="id_nome" name="nome" value="{{ form.nome.value|default_if_none:'' }}" maxlength="100"
            required>
        {% if form.nome.errors %}
        <div class="error">{{ form.nome.errors }}</div>
        {% endif %}
    </div>

    <div>
        <label for="id_data_nascimento">data_nascimento:</label>
        <input type="text" id="id_data_nascimento" name="data_nascimento" value="{{ form.data_nascimento.value|default_if_none:'' }}" maxlength="11"
            required>
        {% if form.data_nascimento.errors %}
        <div class="error">{{ form.data_nascimento.errors }}</div>
        {% endif %}
    </div>

    <button type="submit">Salvar</button>
</form>
<a href="{% url 'lista_alunos'%}">Voltar</a>

gerenciamento/templates/alunos/criar_alunos.html
<h1>Criar Alunos</h1>
<form method="post">
    {% csrf_token %}
    <div>
        <label for="id_nome">Nome:</label>
        <input type="text" id="id_nome" name="nome" value="{{ form.nome.value|default_if_none:'' }}" maxlength="100"
            required>
        {% if form.nome.errors %}
        <div class="error">{{ form.nome.errors }}</div>
        {% endif %}
    </div>

    <div>

        <label for="id_data_nascimento">data_nascimento:</label>
        <input type="text" id="id_data_nascimento" name="data_nascimento" value="{{ form.data_nascimento.value|default_if_none:'' }}" maxlength="11"
            required>
        {% if form.data_nascimento.errors %}
        <div class="error">{{ form.data_nascimento.errors }}</div>
        {% endif %}
    </div>

    <button type="submit">Salvar</button>
</form>
<a href="{% url 'lista_alunos'%}">Voltar</a>

gerenciamento/templates/alunos/deletar_alunos.html
<h1>Deletar Alunos</h1>
<p>Tem certeza que deseja deletar {{ aluno.nome }}?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Deletar</button>
</form>
<a href="{% url 'lista_alunos' %}">Voltar</a>

gerenciamento/templates/alunos/lista_alunos.htm
    <h1>Listar Alunos</h1>
    <a href="{% url 'criar_alunos' %}"> Adicionar Alunos</a>
 
    <ul>
        {% for aluno in alunos %}
            <li>{{aluno.id }} - {{ aluno.nome }} - {{ aluno.data_nascimento }}</li>
              <a href="{% url 'atualizar_alunos' aluno.id %}"> Editar</a>
              <a href="{% url ' deletar_alunos' aluno.id %}">Apagar</a>
        {% endfor %}
    </ul>

gerenciamento/templates/curso/atualizar_curso.html
<h1>Atualizar Curso</h1>
<form method="post">
    {% csrf_token %}
    <div>
        <label for="id_aluno">aluno:</label>
        <input type="number" id="id_aluno" name="aluno" value="{{ form.aluno.value|default_if_none:'' }}" maxlength="100"
            required>
        {% if form.aluno.errors %}
        <div class="error">{{ form.aluno.errors }}</div>
        {% endif %}
    </div>

    <div>
        <label for="id_descricao">Descrição:</label>
        <input type="text" id="id_descricao" name="descricao" value="{{ form.descricao.value|default_if_none:'' }}" maxlength="11"
            required>
        {% if form.descricao.errors %}
        <div class="error">{{ form.descricao.errors }}</div>
        {% endif %}
    </div>

    <div>
        <label for="id_descricao">Valor:</label>
        <input type="number" id="id_valor" name="valor" value="{{ form.valor.value|default_if_none:'' }}" maxlength="9999"
            required>
        {% if form.valor.errors %}
        <div class="error">{{ form.valor.errors }}</div>
        {% endif %}
    </div>

    <button type="submit">Salvar</button>
</form>
<a href="{% url 'lista_cursos' %}">Voltar</a>

gerenciamento/templates/curso/criar_curso.html
<h1>Criar Curso</h1>
<form method="post">
    {% csrf_token %}
    <div>
        <label for="id_curso">curso:</label>
        <input type="number" id="id_curso" name="curso" value="{{ form.curso.value|default_if_none:'' }}" maxlength="100"
            required>
        {% if form.curso.errors %}
        <div class="error">{{ form.curso.errors }}</div>
        {% endif %}
    </div>

    <div>
        <label for="id_descricao">Descrição:</label>
        <input type="text" id="id_valor" name="descricao" value="{{ form.descricao.value|default_if_none:'' }}" maxlength="9999"
            required>
        {% if form.descricao.errors %}
        <div class="error">{{ form.descricao.errors }}</div>
        {% endif %}
    </div>

    <div>
        <label for="id_descricao">Valor:</label>
        <input type="number" id="id_valor" name="valor" value="{{ form.valor.value|default_if_none:'' }}" maxlength="9999"
            required>
        {% if form.valor.errors %}
        <div class="error">{{ form.valor.errors }}</div>
        {% endif %}
    </div>

    <button type="submit">Salvar</button>
</form>
<a href="{% url 'lista_cursos' %}">Voltar</a>

gerenciamento/templates/curso/deletar_curso.html
<h1>Deletar Curso</h1>
<p>Tem certeza que deseja deletar {{ curso.descricao }}?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Deletar</button>
</form>
<a href="{% url 'lista_cursos' %}">Voltar</a>

gerenciamento/templates/curso/lista_cursos.htm
    <h1>Listar Cursos</h1>
    <ul>
        {% for curso in cursos %}
            <li>{{ curso.aluno }} - {{ curso.descricao }} - {{ curso.valor }}</li>
              <a href="{% url 'atualizar_curso' curso.id %}">Editar</a>
              <a href="{% url 'deletar_cursos' curso.id % }"></a>
        {% endfor %}
    </ul>

gerenciamento/templates/matriculas/atualizar_matriculas.html
<h1>Atualizar Curso</h1>
<form method="post">
    {% csrf_token %}
    <div>
        <label for="id_aluno">aluno:</label>
        <input type="number" id="id_aluno" name="aluno" value="{{ form.aluno.value|default_if_none:'' }}" maxlength="100"
            required>
        {% if form.aluno.errors %}
        <div class="error">{{ form.aluno.errors }}</div>
        {% endif %}
    </div>

    <div>
        <label for="id_descricao">Descrição:</label>
        <input type="text" id="id_descricao" name="descricao" value="{{ form.descricao.value|default_if_none:'' }}" maxlength="11"
            required>
        {% if form.descricao.errors %}
        <div class="error">{{ form.descricao.errors }}</div>
        {% endif %}
    </div>

    <div>
        <label for="id_descricao">Valor:</label>
        <input type="number" id="id_valor" name="valor" value="{{ form.valor.value|default_if_none:'' }}" maxlength="9999"
            required>
        {% if form.valor.errors %}
        <div class="error">{{ form.valor.errors }}</div>
        {% endif %}
    </div>

    <button type="submit">Salvar</button>
</form>
<a href="{% url 'lista_cursos' %}">Voltar</a>

gerenciamento/templates/matriculas/lista_matriculas.html
    <h1>Matrículas</h1>
    <ul>
        {% for matricula in matriculas %}
            <li>{{ matricula.aluno.nome }} - {{ matricula.curso.nome }} - {{ matricula.data_matricula }}</li>
            <a href="{% url 'atualizar_curso' curso.id %}">Editar</a>
            <a href="{% url 'deletar_cursos' curso.id % }"></a>
        {% endfor %}
    </ul>